#**Pivot Tables Analysis**

###Number of sessions by traffic channel and device type

In [ ]:
sessions_df = df[['ga_session_id', 'traffic_channel', 'device']].drop_duplicates()


sessions_df = sessions_df.dropna(subset=['traffic_channel', 'device'])
sessions_df = sessions_df[
    (sessions_df['traffic_channel'] != 'unknown') &
    (sessions_df['device'] != 'unknown')
]


pivot_sessions = pd.pivot_table(
    sessions_df,
    index='traffic_channel',
    columns='device',
    values='ga_session_id',
    aggfunc='count',
    fill_value=0
)

pivot_sessions.style \
    .background_gradient(cmap="Blues") \
    .format("{:,.0f}") \
    .set_caption("Sessions by Traffic Channel and Device")

###Top-10 product categories by total sales in Top-5 countries

In [ ]:
df['price'] = pd.to_numeric(df['price'], errors='coerce')


top5_countries = (
    df.groupby('country')['price']
    .sum()
    .sort_values(ascending=False)
    .head(5)
    .index
)


top10_categories = (
    df.groupby('category')['price']
    .sum()
    .sort_values(ascending=False)
    .head(10)
    .index
)


filtered_df = df[
    (df['country'].isin(top5_countries)) &
    (df['category'].isin(top10_categories))
]


pivot_sales = pd.pivot_table(
    filtered_df,
    index='category',
    columns='country',
    values='price',
    aggfunc='sum',
    fill_value=0
)

pivot_sales.style \
    .background_gradient(cmap="Blues") \
    .format("{:,.2f}") \
    .set_caption("Top-10 Categories by Sales in Top-5 Countries")

###Average Order Value (AOV) by Traffic Channel and Device

In [ ]:

filtered_df = df.dropna(subset=['traffic_channel', 'device', 'price'])

pivot_aov = pd.pivot_table(
    filtered_df,
    index='traffic_channel',
    columns='device',
    values='price',
    aggfunc='mean'
)

pivot_aov.style \
    .background_gradient(cmap="Blues") \
    .format("{:,.2f}") \
    .set_caption("Average Order Value by Traffic Channel and Device")

###Sales per Registered User by Country

In [ ]:

sales_country = df.groupby('country')['price'].sum()

users_country = df.groupby('country')['account_id'].nunique()

sales_per_user = (sales_country / users_country).dropna().sort_values(ascending=False).head(10)

pivot_sales_per_user = sales_per_user.to_frame(name='Sales per User')


pivot_sales_per_user.style \
    .background_gradient(cmap="Blues") \
    .format("{:,.2f}") \
    .set_caption("Sales per Registered User by Country")